s="""TCAAGATAAACCCTACCGCAACTCATAGCGGCTTAAGCTTACTCAAGCACGCGAAGGCTT
CTGTCCTCACTGCGCAACTTTGCTAGGTTATCCACAGAATGCCGCGTTTGTTGATTAAGT
GAGTGACGGAATAGGACGCAACTTCTTTGGGCCGGGCACCCCGTAGCGTACCTCAGGTGG
AGCAACGCGTTCGTCGACAGAAGGCAAAGCTCCCGATAAATCAAACTACTATTGTTCCGC
TTACGCACTCGGCTGGGGAAACTAGTAACACGAAAGTCTCATTCAAGTGGCCCCCGTACC
CGATTTCGGCGGTGTTGGCCAGAGCGTACCGGCACTAGTATCGGGCTGAGAACTAGGGTG
GTGGGTTGCAGGGACTATGGCGATGCGCTCCTCAGTGTGCGAAGTTAACTCAATAGGATG
GGTGCGGTAGTTTCAGTATACGCACCTTAGGAGTTTCTCTGTGCCACGATCAGGTCATCT
GGGGAAGCGGTGAATAAGGGCTGTATGCAGTGATTAAACACGACATGCCCGTGAGTTCCA
CTGTGGGTTAGGGTACGTACGATACAAATAGGATCTTACTTGGCCATCTTCGAGACCACA
AAGAATATATGCCCTACTTTAGCGCCAACTTGTGACCGCAGAGGAGCCAATGACGTATTA
ACAAACACCCGACTGGTTGTACCTTCCGCCTGTACGGCCTAACAACCTTCGATTAACTTC
GTAATTCATCCTCACTCTAATTTAGCTTTTACCTACAGCATAAAGTGCCCGCTATAGAAC
CCCAGGTCGCACCATGATGCATGACTTGTGCAAGCGCCTAATAATAATCCCTTGGCGAGG
AAACCAACTGGGCTAGGTGACCACTCAGTTAGGCGCAGTTAATGTACTTAAAAGACGTCG
TCGCCCTAGATGAAAGCCCGAGGCATGCGACTACCAGTAGATATGGCGGCCCGATTAGGG
TGGGTCGGTCAAGAAGGCTGTA"""

t="""ACACACCTGTGGGTTGAAGCGTGGCGGTCGGAAAGGACGAAATCGCAGTCATCTCCCGGA
GCCAGATGACAGACGTACGCCA"""

s=list(s.replace("\n",""))
t=list(t.replace("\n",""))

answer=[]
position=0
for i in range(len(t)):
    for j in range(position,len(s)):
        position +=1
        if t[i]==s[j]:
            answer.append(j+1)
            break
print(*answer)
